### ISSUE TITLE
Test mode for JamfPackageCleaner?

### ISSUE THREAD

**Issue by everetteallen** [grahampugh/jamf-upload#101]
As a feature request, It would be very nice to have a way to do  a run with the JamfPackageCleaner post processor that will just print what would happen instead of actually  doing the delete.  I am tip toeing into a very large clean up  with messy naming and itwould be nice to see just the report first of what would happen.

**Comment by cr3ation** [comment]
I have created [this](https://github.com/grahampugh/jamf-upload/pull/103) pull request that might suite your need.

Please have a look at the pull request. Feedback is appreciated.

You need to run the `JamfPackageCleaner` processor with `--key dry_run=True`. You might also want to raise the limit of the `maximum_allowed_packages_to_delete` key during the dry run.
