### ISSUE TITLE
Documentation: JCDS2 may required new permission for AutoPkg user...

### ISSUE THREAD

**Issue by everetteallen** [grahampugh/jamf-upload#158]
https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-AutoPkg-Processors#jamf-account-privileges
Would be a good idea to mention that the autopkg user may need to add the 
"Jamf Content Distribution Server Files"  with Read and Create permission if working with JCDS2
per the Preparation section of 
https://learn.jamf.com/en-US/bundle/jamf-cloud-distribution-service-release-notes/page/Release_History.html
Thanks!

**Comment by grahampugh** [comment]
Hi @everetteallen 

It already says this:
> If you are using `jcds2_mode` option in conjunction with JamfPackageUploader, you need to add Create privileges on Jamf Content Distribution Server Files.

Is there something missing?

**Comment by everetteallen** [comment]
Nope my bad.  Missed it in all the if's.  Thanks!
