### ISSUE TITLE
JamfPackageUploader fails to set package category

### ISSUE THREAD

**Issue by 1sth1sth1ng0n** [grahampugh/jamf-upload#163]
Using the latest version of `[JamfPackageUploader](https://github.com/grahampugh/jamf-upload/blob/main/JamfUploaderProcessors/JamfPackageUploader.py)` and passing a value to the documented input `pkg_category` does not result in a category being applied to the package in Jamf Cloud.

## Build Versions in use:
```
Jamf Cloud 11.5.1
AutoPkg 2.7.3
```

## Steps to reproduce:
Create an override or use an existing recipe that utilizes `JamfPackageUploader`. Assign a value to the required input variable.
```
CATEGORY: Applications

..........

- Arguments:
    pkg_category: '%CATEGORY%'
  Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader
```

Output successfully shows the category is assigned but end result is a category not being applied to the package in Jamf Cloud. Package category defaults to `None`.
```
The following packages were uploaded to or updated in Jamf Pro:
    Category      Name           Pkg Name                         Pkg Display Name                 Pkg Path                                                                                                    Version
    --------      ----           --------                         ----------------                 --------                                                                                                    -------
    Applications  Google Chrome  Google_Chrome-126.0.6478.57.pkg  Google_Chrome-126.0.6478.57.pkg  /Users/runner/Library/AutoPkg/Cache/local.jamf.Google_Chrome-patch/Google_Chrome-126.0.6478.57.pkg
```
## Expected behavior:
Category gets assigned to package in Jamf Cloud i.e Applications.

**Comment by grahampugh** [comment]
Is this still the case?

**Comment by 1sth1sth1ng0n** [comment]
Pls mark as resolved.
