### ISSUE TITLE
Request for new Processor JamfGroupDeleter 

### ISSUE THREAD

**Issue by katidzehnder** [grahampugh/jamf-upload#168]
As discussed I would like to request a new processor JamfGroupDeleter analog to the com.github.grahampugh.jamf-upload.processors/JamfPolicyDeleter so we can delete Smart Groups after staging.

**Comment by grahampugh** [comment]
`JamfComputerGroupDeleter` has been added to `grahampugh/jamf-upload`. Would be great if you could test.
