### ISSUE TITLE
'vpp_id' could not be successfully determined with JamfUploaderProcessors/JamfUploaderLib/JamfMacAppUploaderBase.py

### ISSUE THREAD

**Issue by katidzehnder** [grahampugh/jamf-upload#171]
I was not able to use the variable vpp_id in our templates any more. But not all of the tenants can use the vpp_id=1

I could not find anything wrong in our recepies , also tried to find anything wrong in the JamfMacAppUploaderBase.py and executing the curl command to get the volume-purchasing-locations did show successful results.

error message:
> JamfMacAppUploader: Replacing existing MAS app as 'replace_macapp' is set to True
> JamfMacAppUploader: Existing bundle ID is 'com.bitwarden.desktop'
> JamfMacAppUploader: Existing MAS app version is '2024.9.0'
> JamfMacAppUploader: Existing MAS app free status is 'True'
> JamfMacAppUploader: Existing MAS URL is 'https://apps.apple.com/ch/app/bitwarden/id1352778147?mt=12'
> JamfMacAppUploader: Existing Self Service icon is 'https://ics.services.jamfcloud.com/icon/hash_42102648ded292cd7f980fd46cd18be31d83c7f2198f780064f7d4a0457c4fce'
> JamfMacAppUploader: WARNING: 'vpp_id' has no replacement object!
> Receipt written to /Users/serveradmin/Library/AutoPkg/Cache/local.jamf.Bitwarden-macapp/receipts/Bitwarden-macapp-receipt-20241011-115221.plist
> 
> The following recipes failed:
>     Bitwarden-macapp.jamf
>         Error in local.jamf.Bitwarden-macapp: Processor: com.github.grahampugh.jamf-upload.processors/JamfMacAppUploader: Error: Unsubstitutable key in template found: 'vpp_id'

**Comment by grahampugh** [comment]
Please post a full, verbose output

**Comment by katidzehnder** [comment]
sorry about that, i found the problem on our side. the API user did not have permissions to 'Read Volume Purchasing Locations'
