### ISSUE TITLE
JamfPackageUploader keeps uploading to JSS even though PKG is present and replace is False

### ISSUE THREAD

**Issue by Lotusshaney** [grahampugh/jamf-upload#172]
> JamfPackageUploader: ID: 797 NAME: iTerm2-3.5.5.pkg
> JamfPackageUploader: Package ID: 797
> JamfPackageUploader: Package 'iTerm2-3.5.5.pkg' already exists: ID 797
> JamfPackageUploader: Number of File Share DPs: 0
> JamfPackageUploader: Handling Cloud Distribution Point
> JamfPackageUploader: Not replacing existing iTerm2-3.5.5.pkg as 'replace_pkg' is set to False. Use replace_pkg='True' to enforce.
> JamfPackageUploader: Checking for existing authentication token
> JamfPackageUploader: Checking https://blahblah.jamfcloud.com against https://blahblah.jamfcloud.com
> JamfPackageUploader: URL and user for token matches current request
> JamfPackageUploader: Existing token is valid
> JamfPackageUploader: Not updating package metadata
> JamfPackageUploader: ID: 797
> JamfPackageUploader: Package 'iTerm2-3.5.5.pkg' metadata exists: ID 797
> JamfPackageUploader: Uploading package to Cloud DP
> JamfPackageUploader: Package upload attempt 1
> JamfPackageUploader: Output file is:  /tmp/jamf_upload_pmrvo45m/jamf_upload_riilpd9_.txt
> JamfPackageUploader: curl command: /usr/bin/curl --location --dump-header /tmp/jamf_upload_pmrvo45m/curl_headers_from_jamf_upload.txt https://blahblah.jamfcloud.com/api/v1/packages/797/upload --header User-Agent: JamfUploader/2024.10.17.0 --request POST --silent --show-error --header authorization: Bearer eyJhbGciOiJIUzI1NiJ9.eyJhdXRoZW50aWNhdGVkLWFwcCI6IkdFTkVSSUMiLCJhdXRoZW50aWNhdGlvbi10eXBlIjoiSlNTIiwiZ3JvdXBzIjpbXSwic3ViamVjdC10eXBlIjoiSlNTX1VTRVJfSUQiLCJ0b2tlbi11dWlkIjoiOGFjMzhhZjgtNjg5My00MDA0LTlkZTEtNGI4OTkzN2EyZGEzIiwibGRhcC1zZXJ2ZXItaWQiOi0xLCJzdWIiOiIxNDQiLCJleHAiOjE3MjkzNTc4NzV9.vDEvW_7nkev-_9NzF8KLB4cVPoCowusGcWV8-Dyb-gc --header Content-type: multipart/form-data --form file=@/Users/blahblah/Library/AutoPkg/Cache/local.munki.iTerm2/iTerm2-3.5.5.pkg --output /tmp/jamf_upload_pmrvo45m/jamf_upload_riilpd9_.txt --cookie-jar /tmp/jamf_upload_pmrvo45m/curl_cookies_from_jamf_upload.txt --cookie /tmp/jamf_upload_pmrvo45m/curl_cookies_from_jamf_upload.txt
> JamfPackageUploader: Package upload 'iTerm2-3.5.5.pkg' upload successful
> JamfPackageUploader: HTTP response: 201

As you can see for the output above, JamfPackageUploader sees the existing PKG in Jamf, Reports its ID and states "Not replacing existing iTerm2-3.5.5.pkg as 'replace_pkg' is set to False. Use replace_pkg='True' to enforce."

However you can see that it does then go ahead and replaces the PKG in jamf.  This happens for all my JamfPackageUploader recipes and started about 2 days ago

**Comment by Lotusshaney** [comment]
Going back and using bb367b380b5f6da47fc031842ef367be620d1788 in the autopkg/grahampugh-recipes repo fixes the problem

**Comment by grahampugh** [comment]
Hi, thanks for this, I'm aware of the problem and working on a fix.

**Comment by grahampugh** [comment]
Hi again, I just pushed a change that hopefully fixes this. Please can you try again?

**Comment by grahampugh** [comment]
Great, then I'll merge the changes over.

**Comment by grahampugh** [comment]
Done
