### ISSUE TITLE
Package Only Upload for JamfUploaderTeamsNotifier incorrect messaging

### ISSUE THREAD

**Issue by rustymyers** [grahampugh/jamf-upload#173]
When running the JamfUploaderTeamsNotifier in a package upload only recipe (does not update a policy or smart group), the post states that "No new packages uploaded." This message is misleading and confusing, since a package was indeed uploaded. Recipe output and image of Teams post attached:

`{'Input': {'JSS_URL': 'https://mdm.tlt.psu.edu:8443',
           'NAME': 'Zotero',
           'POLICY_CATEGORY': 'Productivity',
           'jamfpackageuploader_summary_result': {'data': {'category': 'Productivity',
                                                           'name': 'Zotero',
                                                           'packages_recalculated': 'False',
                                                           'pkg_display_name': 'PSU-Zotero-Universal-7.0.8.pkg',
                                                           'pkg_name': 'PSU-Zotero-Universal-7.0.8.pkg',
                                                           'pkg_path': 'local.jamf.Zotero-PSU/Zotero-7.0.8.pkg',
                                                           'version': '7.0.8'},
                                                  'report_fields': ['category',
                                                                    'name',
                                                                    'pkg_name',
                                                                    'pkg_display_name',
                                                                    'pkg_path',
                                                                    'version',
                                                                    'packages_recalculated'],
                                                  'summary_text': 'The '
                                                                  'following '
                                                                  'packages '
                                                                  'were '
                                                                  'uploaded to '
                                                                  'or updated '
                                                                  'in Jamf '
                                                                  'Pro:'},
           'pkg_name': 'PSU-Zotero-Universal-7.0.8.pkg',
           'teams_webhook_url': 'https://pennstateoffice365.webhook.office.com/...'}}
JamfUploaderTeamsNotifier: No value supplied for teams_username, setting default value of: AutoPkg
JamfUploaderTeamsNotifier: No value supplied for teams_icon_url, setting default value of: https://resources.jamf.com/images/logos/Jamf-Icon-color.png
JamfUploaderTeamsNotifier: JSS address: https://mdm.tlt.psu.edu:8443
JamfUploaderTeamsNotifier: Title: Zotero
JamfUploaderTeamsNotifier: Policy: None
JamfUploaderTeamsNotifier: Version: 7.0.8
JamfUploaderTeamsNotifier: Package: PSU-Zotero-Universal-7.0.8.pkg
JamfUploaderTeamsNotifier: Package Category: None
JamfUploaderTeamsNotifier: Policy Category: Productivity
JamfUploaderTeamsNotifier: Teams webhook post attempt 1
JamfUploaderTeamsNotifier: Teams webhook sent successfully`

<img width="473" alt="Screenshot 2024-10-21 at 9 07 58 AM" src="https://github.com/user-attachments/assets/4dbd68fb-6631-4c76-9485-43be0241759e">

**Comment by jc0b** [comment]
👋 @rustymyers - is the merged change above a suitable solution for you?
