### ISSUE TITLE
curl outputs progress to stderr

### ISSUE THREAD

**Issue by mpanighetti** [grahampugh/jamf-upload#23]
When JamfUploader processes run, they execute `curl` commands in a default mode that outputs progress indicators to stderr. This generates a lot of false positive noise for anyone monitoring stderr for, well, errors. :) If the `curl_cmd` builder step in each script adds the `--silent` and `--show-error` arguments, that would keep the progress indicators from going to stderr (`--silent`) but still send error message results to stderr (`--show-error`), which would be helpful for AutoPkg workflows that monitor for and flag errors found during recipe runs.

Happy to put in a PR for this, but I first wanted to check whether this was a desirable change.

**Comment by grahampugh** [comment]
That's a great find, thanks. No, don't worry about the PR, I have to do it in multiple places so I'll add it myself and test out the consequences.

**Comment by mpanighetti** [comment]
If it helps, `--silent` and `--show-error` are [in the `curl_cmd` used in the URLDownloader processor](https://github.com/autopkg/autopkg/blob/master/Code/autopkglib/URLDownloader.py#L123-L124), so this change would make your processors match default AutoPkg behavior.

**Comment by grahampugh** [comment]
PS I did add this change to the processors in commit 4383b617dd30fa80e6d6713673f23b978a75ccaa
