### ISSUE TITLE
Tripping over substitute_assignable_keys

### ISSUE THREAD

**Issue by armourpeak** [grahampugh/jamf-upload#37]
It seems that in `jamf_script_upload.py`, line 55 is getting tripped up when trying to upload a script that has contains two `%` characters. For example, I have a script that that uses the Jamf API that I am uploading, and in my script I am escaping HTML spaces, with something like: ` "$SERVER"/JSSResource/scripts/name/My%20Great%20Script`.

It is seeing these % characters as surrounding a variable even though I am not  providing any `--key` args.

**Comment by grahampugh** [comment]
Glad you were able to workaround it for now. It'll inevitably come up again at some point though!

**Comment by grahampugh** [comment]
See https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-Tips,-Tricks,-FAQs#how-do-i-handle-importing-a-script-that-genuinely-has-percent-signs-in-it for a workaround.
