### ISSUE TITLE
No value supplied for replace even when replace value is provided

### ISSUE THREAD

**Issue by iannels** [grahampugh/jamf-upload#41]
I am providing the "--replace" value and it is recognized when running the script, but will always stat that the value was not provided so it defaults to false.

**Comment by grahampugh** [comment]
Please can you provide more context? Which script? Provide the full command and output please.

**Comment by iannels** [comment]
In the processor plist, it is writing replace_computergroup = true, but further down in the process it is looking for replace_group. within the jamf-upload.sh script changing the value here from 

elif [[ $processor == "JamfComputerGroupUploader" ]]; then
                if defaults write "$temp_processor_plist" replace_computergroup "True"; then
                    echo "   [jamf-upload] Wrote replace_computergroup='True' into $temp_processor_plist"

to 

elif [[ $processor == "JamfComputerGroupUploader" ]]; then
                if defaults write "$temp_processor_plist" replace_group "True"; then
                    echo "   [jamf-upload] Wrote replace_computergroup='True' into $temp_processor_plist"

This change results in the --replace flag being read properly and updates the jamf smart group.

**Comment by grahampugh** [comment]
Now fixed. Thanks!
