### ISSUE TITLE
Use of undefined key in variable sostituito: 'version'

### ISSUE THREAD

**Issue by nlecchi** [grahampugh/jamf-upload#52]
testing the run of any .jamf recipes it return me this error.

test@myMac ~ % autopkg run -v Firefox.jamf
Processing Firefox.jamf...
Use of undefined key in variable substitution: 'version'
Use of undefined key in variable substitution: 'version'

test@NiL-MBP-338 ~ % autopkg run -v GoogleChrome.jamf
Processing GoogleChrome.jamf...
Use of undefined key in variable substitution: 'version'
Use of undefined key in variable substitution: 'version'

**Comment by grahampugh** [comment]
You can ignore those messages. It is just a by-product of the way AutoPkg processes variables. The JamfUploader processors re-interpret the version string later in the process.
