### ISSUE TITLE
Upload the standalone scripts to pypi

### ISSUE THREAD

**Issue by yairf-s1** [grahampugh/jamf-upload#55]
Could be nice if we would be able to install using pip

**Comment by grahampugh** [comment]
Sorry, but the standalone scripts were just experiments while I was developing the AutoPkg processors. I will be deprecating them soon, except `jamf-api-tool.sh`. 

I made a wrapper script for the AutoPkg processors, `jamf-upload.sh`, which allows you to do the same things as the standalone scripts (except `jamf-api-tool.sh`).
