### ISSUE TITLE
JamfPolicyUploader Conflict "Error: Problem with script"

### ISSUE THREAD

**Issue by rasytesty** [grahampugh/jamf-upload#59]
Hallo Graham,

i'm using your greate JamfPolicyUploader  but i'm getting following Error ( i don't understand why? is that an Issue with script? )

```
com.github.grahampugh.jamf-upload.processors/JamfPolicyUploader
{'Input': {'API_PASSWORD': 'API_PASSWORD',
'API_USERNAME': 'API_USERNAME',
'JSS_URL': 'JSS_URL',
'icon': 'Firefox.png',
'policy_name': 'Install_Firefox',
'policy_template': 'policy_template',
'replace_policy': 'True'}}
JamfPolicyUploader: No value supplied for replace_icon, setting default value of: False
JamfPolicyUploader: File found at: /path/to/policy
JamfPolicyUploader: ("Replacing any instances of 'POLICY_NAME' with", "'Install_Firefox'")
JamfPolicyUploader: ("Replacing any instances of 'NAME' with", "'Firefox'")
JamfPolicyUploader: ("Replacing any instances of 'POLICY_CATEGORY' with", "'Browser'")
JamfPolicyUploader: ("Replacing any instances of 'pkg_name' with", "'Firefox-99.0.pkg'")
JamfPolicyUploader: ("Replacing any instances of 'PATH_TO_APP' with", "'/Applications/Firefox.app'")
JamfPolicyUploader: ("Replacing any instances of 'SELF_SERVICE_DISPLAY_NAME' with", "'Mozilla Firefox'")
JamfPolicyUploader: ("Replacing any instances of 'INSTALL_BUTTON_TEXT' with", "'Install'")
JamfPolicyUploader: ("Replacing any instances of 'REINSTALL_BUTTON_TEXT' with", "'Reinstall'")
JamfPolicyUploader: ("Replacing any instances of 'SELF_SERVICE_DESCRIPTION' with", "'Mozilla Firefox is a free Web Browser.'")
JamfPolicyUploader: Policy data:
JamfPolicyUploader: <?xml version="1.0" encoding="UTF-8"?>
<policy>
<general>
<name>Install_Firefox</name>
<enabled>true</enabled>
<frequency>Ongoing</frequency>
<trigger_other>Install_Firefox</trigger_other>
<category>
<name>Browser</name>
</category>
</general>
<scope>
<all_computers>true</all_computers>
</scope>
<package_configuration>
<packages>
<size>1</size>
<package>
<name>Firefox-99.0.pkg</name>
<action>Install</action>
</package>
</packages>
</package_configuration>
<scripts>
<size>1</size>
<script>
<id>1</id>
<name>dockutil_add</name>
<priority>After</priority>
<parameter4>/Applications/Firefox.app</parameter4>
</script>
</scripts>
<self_service>
<use_for_self_service>true</use_for_self_service>
<self_service_display_name>Mozilla Firefox</self_service_display_name>
<install_button_text>Install</install_button_text>
<reinstall_button_text>Reinstall</reinstall_button_text>
<self_service_description>Mozilla Firefox is a free Web Browser.</self_service_description>
<feature_on_main_page>false</feature_on_main_page>
</self_service>
<maintenance>
<recon>true</recon>
</maintenance>
</policy>
JamfPolicyUploader: Checking for existing 'Install_Firefox' on JSS_URL
JamfPolicyUploader: Checking for existing authentication token
JamfPolicyUploader: Checking JSS_URL against JSS_URL
JamfPolicyUploader: URL for token matches current request
JamfPolicyUploader: Existing token is valid
JamfPolicyUploader: Existing cookie found: APBALANCEID=APBALANCEID
JamfPolicyUploader: Jamf Pro Version: 10.37.2-t1648851072
JamfPolicyUploader: Token auth will be used,
JamfPolicyUploader: Existing cookie found: APBALANCEID=APBALANCEID
JamfPolicyUploader: Policy 'Install_Firefox' already exists: ID 225
JamfPolicyUploader: Replacing existing policy as 'replace_policy' is set to True
JamfPolicyUploader: Uploading Policy...
JamfPolicyUploader: Policy upload attempt 1
JamfPolicyUploader: Existing cookie found: APBALANCEID=APBALANCEID
JamfPolicyUploader: b'<html>\n<head>\n <title>Status page</title>\n</head>\n<body style="font-family: sans-serif;">\n<p style="font-size: 1.2em;font-weight: bold;margin: 1em 0px;">Conflict</p>\n<p>Error: Problem with script</p>\n<p>You can get technical details <a href="[http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10">here</a>.<br>\nPlease](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.10%22%3Ehere%3C/a%3E.%3Cbr%3E\nPlease) continue your visit at our <a href="/">home page</a>.\n</p>\n</body>\n</html>\n'
WARNING: Policy 'Install_Firefox' update failed due to a conflict
Failed.
Receipt written to /path/to/cached/recipe
```

**Comment by grahampugh** [comment]
Does the script `dockutil_add` exist on the server already?

**Comment by rasytesty** [comment]
yes, it exists

**Comment by grahampugh** [comment]
It's not called dockutil_add.sh or something like that? The name has to be exact.

**Comment by rasytesty** [comment]
that is the exact Name on Server. Everything was running without any Problem

**Comment by rasytesty** [comment]
i just built the exact policy without adding script "dockutil_add" and it works fine but once i add script, it throws an Error

**Comment by grahampugh** [comment]
Can you post the recipe and the full output please? Hard to properly diagnose from partial output and without seeing the input.

**Comment by grahampugh** [comment]
Ah, I think I see the problem. You have a script id set in the policy, but you shouldn't do that, because you can't guarantee which id it will be. Just remove the line, it's not needed.

**Comment by grahampugh** [comment]
Let me see your policyTemplate.xml please.

**Comment by rasytesty** [comment]
that is my policyTemplate.xml thanks for checking ;) 


`<?xml version="1.0" encoding="UTF-8"?>
<policy>
	<general>
		<name>%POLICY_NAME%</name>
		<enabled>true</enabled>
		<frequency>Ongoing</frequency>
		<trigger_other>Install_%NAME%</trigger_other>
		<category>
			<name>%POLICY_CATEGORY%</name>
		</category>
	</general>
	<scope>
        <all_computers>true</all_computers>
	</scope>
	<package_configuration>
		<packages>
			<size>1</size>
			<package>
				<name>%pkg_name%</name>
				<action>Install</action>
			</package>
		</packages>
	</package_configuration>
	<scripts>
		<size>1</size>
        <script>
			<name>dockutil_add</name>
			<priority>After</priority>
			<parameter4>%PATH_TO_APP%</parameter4>
		</script>
	</scripts>
	<self_service>
		<use_for_self_service>true</use_for_self_service>
		<self_service_display_name>%SELF_SERVICE_DISPLAY_NAME%</self_service_display_name>
		<install_button_text>%INSTALL_BUTTON_TEXT%</install_button_text>
		<reinstall_button_text>%REINSTALL_BUTTON_TEXT%</reinstall_button_text>
		<self_service_description>%SELF_SERVICE_DESCRIPTION%</self_service_description>
		<feature_on_main_page>false</feature_on_main_page>
	</self_service>
	<maintenance>
		<recon>true</recon>
	</maintenance>
</policy>`

**Comment by grahampugh** [comment]
OK, nothing wrong with that. The only real reason that "Problem with Script" comes up is because the script named in the policy template cannot be found. I just had the same problem but it was because I had forgotten to upload the script to that particular Jamf instance. 

I think you need to double-check the script name. Better still, include the script in your recipe, then there's no doubt about the script matching...

**Comment by rasytesty** [comment]
my Bad, it was permission Issue, autopkg user didn't have Script Permissions in Jamf (read create update delete) none of them was selected. 
it's strange, i used the JamfPolicyUploader the whole time (without need to give Autopkg Script-Permissions.
thank u so much for your Supporting :)
