### ISSUE TITLE
Can not configure DPs 

### ISSUE THREAD

**Issue by marckerr** [grahampugh/jamf-upload#67]
AutoPkg 2.4.1, AutoPkgr 1.6, current jamf-upload, macOS 12.4, M1
In the Intergrations section of AutoPkgr, when configuring JamfUploader with DP settings of type Local, SMB or AFP I'm only able to enter anything in the Password field, and Port for SMB and AFP. All of the other fields are uneditable. So I'm not able to save the configuration

**Comment by grahampugh** [comment]
Correct, this is not an issue with JamfUploader. AutoPkgr does not have full compatibility yet. Follow the instructions in the JamfUploader wiki for adding your JamfUploader credentials to the AutoPkg preferences file.
