### ISSUE TITLE
Feature Request: local drive support for PackageUploader Processor

### ISSUE THREAD

**Issue by ddcdennisb** [grahampugh/jamf-upload#75]
Would love to see local drive support brought into uploader.

**Comment by grahampugh** [comment]
I believe this is now implemented.

**Comment by ddcdennisb** [comment]
@grahampugh I believe there is still some work that needs to be done.  I've added the SMB keys and using file://path/to/repo in the SMB_URL, but getting and error when trying to run the packageupload processor.  
![Screenshot 2022-11-29 at 07 59 24](https://user-images.githubusercontent.com/15944894/204535837-bcc7164f-27e7-404e-b52b-eebb68895777.png)
