### ISSUE TITLE
upload of larger pkgs (> 1GB) fails with jamf uploader

### ISSUE THREAD

**Issue by inglenny** [grahampugh/jamf-upload#90]
Somehow uploading pkgs which are larger than 1 GB fails. The curl process hangs almost always at exactly 1,12 GB. Tried it with a different mac, same error. Different network connection, same error. 

We are using Jamf Cloud. 

Any idea what that could be?

I tried it with autopkg processors and manually with the jamf_pkg_upload.py. Stops exactly at the same time.

Thanks for your help

lenny

**Comment by grahampugh** [comment]
Try `jcds_mode` if you're using Jamf Cloud. See https://grahamrpugh.com/2022/04/19/jamfuploader-jcds-mode.html for details.

**Comment by inglenny** [comment]
Thank you for the tip. I tried adding 

`<key>jcds_mode</key>
<string>True</string>`

to the recipe. Which seems to have worked:

`JamfPackageUploader: Uploading package using experimental JCDS mode`

However I'm getting this error message:

`Error in xxx: Processor: com.github.grahampugh.jamf-upload.processors/JamfPackageUploader: Error: WARNING: No package upload session token was found`

Uploading via curl works with other packages, so I guess my API credentials are fine. Or is there something else I need to add?

**Comment by grahampugh** [comment]
Please note the instructions regarding permissions for JCDS mode here: https://github.com/grahampugh/jamf-upload/wiki/JamfUploader-AutoPkg-Processors#jamf-account-privileges

**Comment by inglenny** [comment]
Now I remember that I read that already. Thanks for the heads up. I will try again.

**Comment by inglenny** [comment]
After setting Update privileges on SSO settings the upload works perfectly fine with JCDS.

Any idea why we are having issues with the default upload method?

**Comment by grahampugh** [comment]
You'd have to ask Jamf that. Both methods use unsupported APIs, because Jamf is yet to provide an official package upload endpoint.
